import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('WA_Fn-UseC_-HR-Employee-Attrition.csv')
plt.figure(figsize=(6,6))
df['Attrition'].value_counts().plot(kind='pie', autopct='%1.1f%%', colors=['lightgreen','lightcoral'])
plt.title('Overall Attrition')
plt.ylabel('')
plt.show()
attrition_dept = df.groupby('Department')['Attrition'].apply(lambda x: (x=='Yes').mean()*100).sort_values(ascending=False)
plt.figure(figsize=(10,5))
sns.barplot(x=attrition_dept.index, y=attrition_dept.values)
plt.title('Attrition Rate by Department %')
plt.xticks(rotation=45)
plt.show()
plt.figure(figsize=(10,5))
sns.countplot(data=df, x='Age', hue='Attrition')
plt.title('Attrition by Age')
plt.show()
plt.figure(figsize=(6,4))
sns.barplot(data=df, x='OverTime', y=(df['Attrition']=='Yes').astype(int)*100)
plt.title('Attrition % by Overtime')
plt.ylabel('Attrition %')
plt.show()
pivot = df.pivot_table(index='JobRole', columns='OverTime', values='Attrition', aggfunc=lambda x: (x=='Yes').mean()*100)
plt.figure(figsize=(12,6))
sns.heatmap(pivot, annot=True, fmt='.1f', cmap='Reds')
plt.title('Attrition % by JobRole and Overtime')
plt.show()
